/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlines;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kunal
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        initComponents();
        GetTicket();
        Cfcode.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cfcode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Ctid = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cancellationtable = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        Cfdate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Ticket ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 160, 30));

        Cfcode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(Cfcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 156, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Flight date");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 100, 150, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("CANCEL FLIGHT");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 200, 40));

        Ctid.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ctid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CtidActionPerformed(evt);
            }
        });
        jPanel1.add(Ctid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 161, 30));

        Cancellationtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Cancellationtable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1510, 480));

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 51, 255));
        jTextField3.setText("Cancellation List ");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, 200, 40));

        Back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 102, 255));
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        jPanel1.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 240, 160, 30));

        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(0, 102, 255));
        Cancel.setText("Cancel");
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 160, 30));

        Reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Reset.setForeground(new java.awt.Color(0, 102, 255));
        Reset.setText("Reset");
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
        });
        jPanel1.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 160, 30));
        jPanel1.add(Cfdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 150, 157, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("Flight Code");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 150, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("X");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 0, 10, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("X");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 10, 10, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1514, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
Connection Con =null;
  Statement St = null,St1=null;
  java.sql.PreparedStatement pst = null;
  ResultSet Rs = null,Rs1=null;

private void DisplayCanc(){
 try{
 Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb","root","");
 St = Con.createStatement();
 Rs = St.executeQuery("Select*  from  cancellationTbl");
 Cancellationtable.setModel(DbUtils.resultSetToTableModel(Rs));
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e);
 }
}


int Cid =1;

private void CountCanc(){
    try{
    St1 = Con.createStatement();
    Rs1=St1.executeQuery("Select Max(Cancid) from cancellationTbl");
    Rs1.next();
    Cid= Rs1.getInt(1)+1;
    }
    catch(Exception e){
   }
   }



  private void GetTicket(){
 try{
 Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb","root","");
 St = Con.createStatement();
 String Query = "Select *  from  bookingstbl";
 Rs = St.executeQuery(Query);
  while(Rs.next()){
  int T= Rs.getInt("Ticketid");
  Ctid.addItem(String.valueOf(T));
  }  
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e);
 }
}
 
  private void GetFcode(){
 try{
 Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb","root","");
 St = Con.createStatement();
 String Query = "Select*  from  bookingsTbl where Ticketid ="+Ctid.getSelectedItem().toString();
 Rs = St.executeQuery(Query);
  if(Rs.next()){
  Cfcode.setText(Rs.getString("Flcode"));
  }  
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e);
 }
}
  
  
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
   new MainForm().setVisible(true); 
   this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
    if(Cfcode.getText().isEmpty()){
     JOptionPane.showMessageDialog(this,"Missing Information");
     }  
     else{
     try{
     CountCanc();
     Con =  DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb","root","");
     java.sql.PreparedStatement Add = Con.prepareStatement("Insert into cancellationtbl VALUES(?,?,?,?)");
     Add.setInt(1,Cid);
     Add.setInt(2,Integer.valueOf(Ctid.getSelectedItem().toString()));
     Add.setString(3,Cfcode.getText());
     Add.setString(4, Cfdate.getDate().toString());
    
     int row = Add.executeUpdate();
     JOptionPane.showMessageDialog(this,"Ticket Cancel");
     Con.close();
     Cancel();
     DisplayCanc();
    // Clear();
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(this, e);
     }
     }
    }//GEN-LAST:event_CancelMouseClicked

    private void Cancel(){
     try{
     Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb","root","");
     String Query = "Delete from FlightTbl where Ticketid="+Ctid.getSelectedItem().toString();
     Statement Del = Con.prepareStatement(Query);
     Del.executeUpdate(Query);
     }
     catch(Exception e){
     JOptionPane.showMessageDialog(this,e);
     }
     }
    
    
    private void CtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CtidActionPerformed
       GetFcode();  
    }//GEN-LAST:event_CtidActionPerformed

    
    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
      Cfcode.setText("");
    }//GEN-LAST:event_ResetMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JTable Cancellationtable;
    private javax.swing.JTextField Cfcode;
    private com.toedter.calendar.JDateChooser Cfdate;
    private javax.swing.JComboBox<String> Ctid;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
