/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package airlines;

import java.sql.*;
import java.sql.PreparedStatement;
/**
 *
 * @author kunal
 */
import net.proteanit.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Passengers extends javax.swing.JFrame {

    /**
     * Creates new form Passengers
     */
    public Passengers() {
        initComponents();
        DisplayPassengers();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nationcb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Gencb = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        PassNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PAdd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ptablelist = new javax.swing.JTable();
        jTextField3 = new javax.swing.JTextField();
        Pedit = new javax.swing.JButton();
        PSAve = new javax.swing.JButton();
        Pback = new javax.swing.JButton();
        Pdelete = new javax.swing.JButton();
        Phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("X");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 0, 10, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("X");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 10, 20, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Nationality");

        Nationcb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Nationcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian", "USA", "UK", "Spain", "France", "Germany", "Japan", "South Korea", "Russia", "Isarel", "Sri Lanka" }));
        Nationcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NationcbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("Gender");

        Gencb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Gencb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other", "Not to Say" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("Passport Number");

        Pname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PassNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("Passenger Name");

        PAdd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("Address");

        Ptablelist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Ptablelist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PtablelistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ptablelist);

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 51, 255));
        jTextField3.setText("Passengers List ");
        jTextField3.setBorder(null);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        Pedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pedit.setForeground(new java.awt.Color(0, 102, 255));
        Pedit.setText("Edit");
        Pedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PeditMouseClicked(evt);
            }
        });

        PSAve.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PSAve.setForeground(new java.awt.Color(0, 102, 255));
        PSAve.setText("Save");
        PSAve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PSAveMouseClicked(evt);
            }
        });

        Pback.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pback.setForeground(new java.awt.Color(0, 102, 255));
        Pback.setText("Back");
        Pback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PbackMouseClicked(evt);
            }
        });

        Pdelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Pdelete.setForeground(new java.awt.Color(0, 102, 255));
        Pdelete.setText("Delete");
        Pdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PdeleteMouseClicked(evt);
            }
        });

        Phone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 102, 255));
        jLabel9.setText("Phone");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 102, 255));
        jLabel10.setText("PASSENGER DETAIL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(Pname))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nationcb, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Gencb, 0, 130, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PassNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(PAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Phone)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(628, 628, 628)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(PSAve, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(Pedit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(Pback, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100)
                        .addComponent(Pdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1534, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nationcb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gencb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PSAve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pedit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pback, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection Con =null;
Statement St = null,St1=null;
PreparedStatement pst = null;
ResultSet Rs = null,Rs1=null;
 
private void DisplayPassengers(){
 try{
 Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb","root","");
 St = Con.createStatement();
 Rs = St.executeQuery("Select*  from  passengersTbl");
 Ptablelist.setModel(DbUtils.resultSetToTableModel(Rs));
 }
 catch(Exception e){
 JOptionPane.showMessageDialog(this, e);
 }
}
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void NationcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NationcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NationcbActionPerformed
    int Passid =0;
    private void CountPassengers(){
    try{
    St1 = Con.createStatement();
    Rs1=St1.executeQuery("select Max(Pid) from passengersTbl");
    Rs1.next();
    Passid = Rs1.getInt(1)+1;
    }
    catch(Exception e){
    }
    }
    
    private void Clear(){
    Pname.setText("");
    PassNo.setText("");
    PAdd.setText("");
    Phone.setText("");
    }
    private void PSAveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PSAveMouseClicked
    // Check for empty fields
    if (Pname.getText().isEmpty() || PassNo.getText().isEmpty() || PAdd.getText().isEmpty() || Phone.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Missing Information");
        return; // Exit if any field is empty
    }

    try {
        // Establish connection
        Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb", "root", "");

        // Check for duplicate passport numbers
        PreparedStatement checkStmt = Con.prepareStatement("SELECT COUNT(*) FROM passengerstbl WHERE PPass = ?");
        checkStmt.setString(1, PassNo.getText());
        ResultSet rs = checkStmt.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "A passenger with this passport number already exists.");
            return; // Exit if the passport number already exists
        }

        // Check for existing passengers with the same details
        PreparedStatement existingCheckStmt = Con.prepareStatement("SELECT COUNT(*) FROM passengerstbl WHERE Pname = ? AND PPass = ? AND PAdd = ? AND Pphone = ?");
        existingCheckStmt.setString(1, Pname.getText());
        existingCheckStmt.setString(2, PassNo.getText());
        existingCheckStmt.setString(3, PAdd.getText());
        existingCheckStmt.setString(4, Phone.getText());
        ResultSet existingRs = existingCheckStmt.executeQuery();

        if (existingRs.next() && existingRs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "This passenger is already added with the same details.");
            return; // Exit if the passenger with the same details exists
        }

        // Count passengers to assign a new ID
        CountPassengers();

        // Prepare statement to insert new passenger
        PreparedStatement Add = Con.prepareStatement("INSERT INTO passengerstbl VALUES(?,?,?,?,?,?,?)");
        Add.setInt(1, Passid);
        Add.setString(2, Pname.getText());
        Add.setString(3, Nationcb.getSelectedItem().toString());
        Add.setString(4, Gencb.getSelectedItem().toString());
        Add.setString(5, PassNo.getText());
        Add.setString(6, PAdd.getText());
        Add.setString(7, Phone.getText());

        // Execute insertion
        int row = Add.executeUpdate();
        JOptionPane.showMessageDialog(this, "Passenger Added");
        Con.close();
        DisplayPassengers();
        Clear();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e);
    }
    }//GEN-LAST:event_PSAveMouseClicked
    
    private void PdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PdeleteMouseClicked
      if (key == 0) {
        JOptionPane.showMessageDialog(this, "Select a passenger");
    } else {
        try {
            // Establish the connection
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb", "root", "");
            
            // Use a PreparedStatement for safer query execution
            String query = "DELETE FROM PassengersTbl WHERE Pid = ?";
            PreparedStatement delStmt = Con.prepareStatement(query);
            delStmt.setInt(1, key); // Set the passenger ID to delete
            
            // Execute the update
            int rowsAffected = delStmt.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Passenger Deleted");
                DisplayPassengers(); // Refresh the list
                Clear(); // Clear input fields
            } else {
                JOptionPane.showMessageDialog(this, "No passenger found with the selected ID.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } finally {
            // Close the connection in the 'finally' block to avoid resource leaks
            try {
                if (Con != null) {
                    Con.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error closing connection: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_PdeleteMouseClicked

    private void PtablelistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtablelistMouseClicked
     DefaultTableModel model = (DefaultTableModel) Ptablelist.getModel();
     int myindex = Ptablelist.getSelectedRow();
     key = Integer.valueOf(model.getValueAt(myindex, 0).toString());
     Pname.setText(model.getValueAt(myindex,1).toString());
     Nationcb.setSelectedItem(model.getValueAt(myindex, 2).toString());
     Gencb.setSelectedItem(model.getValueAt(myindex, 3).toString());
     PassNo.setText(model.getValueAt(myindex,4).toString());
     PAdd.setText(model.getValueAt(myindex,5).toString());
     Phone.setText(model.getValueAt(myindex,6).toString());
    }//GEN-LAST:event_PtablelistMouseClicked

    private void PbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PbackMouseClicked
    new MainForm().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_PbackMouseClicked

    private void PeditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeditMouseClicked
     if (key == 0) {
        JOptionPane.showMessageDialog(this, "Select a Passenger");
    } else {
        Connection con = null;
        PreparedStatement checkStmt = null;
        PreparedStatement updateStmt = null;

        try {
            // Establish the connection to the database
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/airlinesdb", "root", "");

            // Check if the passport number already exists
            String checkQuery = "SELECT COUNT(*) FROM PassengersTbl WHERE PPass = ? AND Pid <> ?";
            checkStmt = con.prepareStatement(checkQuery);
            checkStmt.setString(1, PassNo.getText()); // Check for the entered passport number
            checkStmt.setInt(2, key); // Exclude the current passenger ID
            
            ResultSet rs = checkStmt.executeQuery();
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "This passport number is already in use by another passenger.");
                return; // Exit if the passport number is a duplicate
            }

            // Proceed to update the passenger details
            String updateQuery = "UPDATE PassengersTbl SET Pname=?, PNat=?, PGen=?, PPass=?, PAdd=?, Pphone=? WHERE Pid=?";
            updateStmt = con.prepareStatement(updateQuery);
            updateStmt.setString(1, Pname.getText());
            updateStmt.setString(2, Nationcb.getSelectedItem().toString());
            updateStmt.setString(3, Gencb.getSelectedItem().toString());
            updateStmt.setString(4, PassNo.getText());
            updateStmt.setString(5, PAdd.getText());
            updateStmt.setString(6, Phone.getText());
            updateStmt.setInt(7, key); // Set the ID of the passenger being updated
            
            // Execute the update
            int rowsAffected = updateStmt.executeUpdate();
            
            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Passenger Updated Successfully");
                DisplayPassengers(); // Refresh the passenger list
                Clear(); // Clear input fields
            } else {
                JOptionPane.showMessageDialog(this, "No passenger found with the selected ID.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } finally {
            // Close resources in the 'finally' block to ensure they are closed even if an exception occurs
            try {
                if (checkStmt != null) checkStmt.close();
                if (updateStmt != null) updateStmt.close();
                if (con != null) con.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error closing connection: " + e.getMessage());
            }
        }
    }
    }//GEN-LAST:event_PeditMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel19MouseClicked
   int key =0;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Gencb;
    private javax.swing.JComboBox<String> Nationcb;
    private javax.swing.JTextField PAdd;
    private javax.swing.JButton PSAve;
    private javax.swing.JTextField PassNo;
    private javax.swing.JButton Pback;
    private javax.swing.JButton Pdelete;
    private javax.swing.JButton Pedit;
    private javax.swing.JTextField Phone;
    private javax.swing.JTextField Pname;
    private javax.swing.JTable Ptablelist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
